# Generated by Django 5.1.7 on 2025-03-18 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=250)),
                ('unit_number', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('province', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='home.address'),
        ),
    ]
